- name: "Obtain working directory path for your filesystem"
  shell: pwd
  register: printed_working_directory

- name: "Set pwd to the value obtained above"
  set_fact:
     pwd: '{{ item }}'
  with_items:
      - '{{ printed_working_directory.stdout_lines }}'

- name:
  debug:
    msg: '{{ pwd }}'

- name: "Call apply.yml when revert equals false"
  include: tasks/apply.yml
  when: "revert == false"

- name: "Call revert.yml when revert equals true"
  include: tasks/revert.yml
  when: "revert == true"

